### ISSUE TITLE
Implement the mandatory L2CAP parts

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/rubble#37]
These would be:

* [ ] `0x0004`: Attribute protocol (ATT) (will be partially implemented as part of https://github.com/jonas-schievink/rubble/issues/29)
* [ ] `0x0005`: LE L2CAP signaling channel (https://github.com/jonas-schievink/rubble/issues/35)
* [ ] `0x0006`: LE Security Manager protocol (https://github.com/jonas-schievink/rubble/issues/36)
